name:                BeginnerTrackExercises
version:             0.1.0.0
github:              "lbuchli/BeginnerTrackExercises"
license:             BSD3
author:              "Lukas Buchli"
copyright:           "2023 Lukas Buchli"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/lbuchli/BeginnerTrackExercises#readme>

dependencies:
- base >= 4.7 && < 5
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  BeginnerTrackExercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BeginnerTrackExercises

tests:
  BeginnerTrackExercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BeginnerTrackExercises
